export const UI = {
    DIALOG: {
        IS_OPEN_DIALOG: 'IS_OPEN_DIALOG',
        SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
        SWITCH_STEP: 'SWITCH_STEP',
        ON_CHANGE_USER_INFO: 'ON_CHANGE_USER_INFO',
        IS_CHECK_ERROR_SUCCESS: 'IS_CHECK_ERROR_SUCCESS'
    }
};